# Server Configuration
server.port=8080
spring.application.name=netflix-system

# Cassandra Configuration
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=netflix
spring.cassandra.local-datacenter=datacenter1

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=netflix-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/netflix
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.sudhir512kj.netflix=DEBUG
logging.level.org.springframework.kafka=INFO