spring:
  profiles:
    active: ${ACTIVE_PROFILE:parkinglot}

---
spring:
  config:
    activate:
      on-profile: webclient
  application:
    name: webclient-demo
server:
  port: 8092
logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always